environments:
  - name: ENV
    value: uat
  - name: EUREKA_DEFAULT_ZONE
    value: uat-eureka-eureka-service.uat-ha-eureka.svc.cluster.local:8761

mountSecrets: true
fullnameOverride: "client-service"

initContainers:
  # - name: secrets
  #   image: gcr.io/google.com/cloudsdktool/cloud-sdk:326.0.0-alpine
  #   env:
  #     - name: DEPLOY_ENV
  #       value: sandbox
  #   #TODO better get from echo "export JWT_SECRET='$(gcloud secrets versions access latest --secret=jwt_secret --project=mine-darts-${DEPLOY_ENV})'" >> /data/secret_env.env;
  #   # command:
  #   #   - "/bin/bash"
  #   #   - "-c"
  #   #   - |
  #   #     set -e
  #   #     echo "export JWT_SECRET='$(gcloud secrets versions access latest --secret=jwt_secret --project=mine-darts-${DEPLOY_ENV})'" >> /data/secret_env.env;
  #   volumeMounts:
  #     - name: config-data
  #       mountPath: /data
env: uat
configMap:
  DATABASE_URL: jdbc:mysql://uat-ha-db.cpxnfotp32ui.ap-east-1.rds.amazonaws.com:3306/ha_local?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
  REDIS_HOST: redis-service.uat-ha-redis.svc.cluster.local
  TEST: KKK

