apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: {{ printf "http-%s-port" (include "api.fullname" .) | trunc 15 | trimSuffix "-" }}
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}