apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}
data:
  EUREKA_DEFAULT_ZONE: http://eureka-service.uat-ha-eureka.svc.cluster.local/eureka/
  DATABASE_URL: jdbc:mysql://uat-ha-db.cpxnfotp32ui.ap-east-1.rds.amazonaws.com:3306/ha_local?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false

