apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}
data:
  DATABASE_URL: jdbc:mysql://uat-ha-db.cpxnfotp32ui.ap-east-1.rds.amazonaws.com:3306/ha_local?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
  CLIENT_SERVICE_URL: http://client-service.uat-ha-client.svc.cluster.local
  REDIS_HOST: redis-service.uat-ha-redis.svc.cluster.local
  IS_PRODUCTION: 'false'


