apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: {{ .Values.containerPort }}
    name: http
  selector:
    run: {{ .Chart.Name }}