apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
  - name: https
    port: 443
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
  selector:
    run: {{ .Chart.Name }}