apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }} 
  namespace: {{ .Values.namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 5 
  selector:
    matchLabels:
      run: {{ .Chart.Name }}  
  template:
    metadata:     
      labels:
        run: {{ .Chart.Name }}  
    spec:    
      serviceAccountName: {{ include "api.serviceAccountName" . }}      
      containers:
        - name: {{ .Chart.Name }}         
          image: redis:7.0.9-alpine
          imagePullPolicy: Always
          args:
          - "--save"
          - ""
          - "--appendonly"
          - "no"
          env:
            - name: ARGOCD_REDIS_SERVICE
              value: ""
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.mountSecrets }}
          volumeMounts:
            - name: config-data
              mountPath: /data
              readOnly: true
          {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.mountSecrets }}
      volumes:
        - name: config-data
          emptyDir: {}
      {{- end }}       